name: Monitor de Pantalones
on:
  schedule:
    - cron: '0 * * * *' # Se ejecuta cada 1 hora en punto
  workflow_dispatch: # Botón manual

jobs:
  check-stock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install puppeteer

      - name: Instalar motor del robot
        run: npx puppeteer browsers install chrome

      - name: Correr Robot 🤖
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_ID: ${{ secrets.TELEGRAM_ID }}
        run: node robot.js
