name: Monitor de Pantalones
on:
  schedule:
    - cron: '0 * * * *' # Se ejecuta cada 1 hora
  workflow_dispatch: # Botón para probarlo a mano

jobs:
  check-stock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install puppeteer
      - name: Correr Robot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_ID: ${{ secrets.TELEGRAM_ID }}
        run: node robot.js
